CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), external_hash TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS platforms (id SERIAL PRIMARY KEY, name TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS posts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), platform_id INT REFERENCES platforms(id), platform_post_id TEXT NOT NULL, author_id_hash TEXT NOT NULL, text TEXT NOT NULL, language TEXT, timestamp TIMESTAMPTZ NOT NULL, raw_payload JSONB NOT NULL DEFAULT '{}', like_count INT DEFAULT 0, share_count INT DEFAULT 0, reply_count INT DEFAULT 0, view_count INT DEFAULT 0, url TEXT, metadata JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(platform_id, platform_post_id));
CREATE TABLE IF NOT EXISTS comments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), post_id UUID REFERENCES posts(id), author_id_hash TEXT, text TEXT, timestamp TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS topics (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), slug TEXT UNIQUE NOT NULL, name TEXT NOT NULL, description TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS topic_mentions (topic_id UUID REFERENCES topics(id), post_id UUID REFERENCES posts(id), confidence NUMERIC, PRIMARY KEY(topic_id, post_id));
CREATE TABLE IF NOT EXISTS sentiment_results (post_id UUID PRIMARY KEY REFERENCES posts(id), label TEXT NOT NULL, confidence NUMERIC, model_version TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS emotion_results (post_id UUID PRIMARY KEY REFERENCES posts(id), label TEXT NOT NULL, confidence NUMERIC, model_version TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS embeddings (post_id UUID PRIMARY KEY REFERENCES posts(id), model_version TEXT NOT NULL, vector JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS entities (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), post_id UUID REFERENCES posts(id), label TEXT, value TEXT);
CREATE TABLE IF NOT EXISTS relationships (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), source_id TEXT NOT NULL, target_id TEXT NOT NULL, relation TEXT NOT NULL, evidence_post_id UUID REFERENCES posts(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS trend_snapshots (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), topic_id UUID REFERENCES topics(id), mention_count INT, velocity NUMERIC, acceleration NUMERIC, engagement_velocity NUMERIC, trend_score NUMERIC, captured_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS narratives (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), topic_id UUID REFERENCES topics(id), title TEXT NOT NULL, summary TEXT, first_seen TIMESTAMPTZ, last_seen TIMESTAMPTZ, post_count INT, platform_count INT, growth_rate NUMERIC, confidence NUMERIC);
CREATE TABLE IF NOT EXISTS narrative_posts (narrative_id UUID REFERENCES narratives(id), post_id UUID REFERENCES posts(id), PRIMARY KEY(narrative_id, post_id));
CREATE TABLE IF NOT EXISTS coordination_signals (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), narrative_id UUID REFERENCES narratives(id), title TEXT, accounts_involved INT, time_window_seconds INT, semantic_similarity NUMERIC, explanation JSONB, evidence_post_ids JSONB, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS investigation_events (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), narrative_id UUID REFERENCES narratives(id), event_type TEXT, detail TEXT, occurred_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS demographic_aggregates (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), dimension TEXT, label TEXT, value NUMERIC, minimum_group_size INT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS system_events (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), event_type TEXT, payload JSONB, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS posts_timestamp_idx ON posts(timestamp DESC);
CREATE INDEX IF NOT EXISTS posts_platform_idx ON posts(platform_id, platform_post_id);
CREATE INDEX IF NOT EXISTS relationships_source_idx ON relationships(source_id);
